name: tuc
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - ffmpeg
  - yt-dlp
  - numpy
  - pandas
  - pyyaml
  - typer
  - click
  - librosa
  - pysoundfile
  - tqdm
  - libffi
  - vc14_runtime
  - ucrt
