name: tuc
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.8
  - ffmpeg
  - yt-dlp
  - numpy
  - pandas
  - pyyaml
  - typer
