species: cornsnake

positive_pairs:
  - { text: "rapid tail vibration",         anchor: tail_vibration,      weight: 1.0 }
  - { text: "forceful hissing (exhalation)",anchor: defensive_hiss,      weight: 1.0 }
  - { text: "body flattening posture",      anchor: body_flattening,     weight: 1.0 }
  - { text: "tight S-shaped coil",          anchor: s_coil_pose,         weight: 1.0 }
  - { text: "Fast bluff strike to scare threats",                  anchor: bluff_strike,          weight: 1.0 }
  - { text: "Release of foul-smelling musk for chemical defense",  anchor: musking,               weight: 1.0 }
  - { text: "Freezing immobility for camouflage",                  anchor: freezing,              weight: 1.0 }
  - { text: "Rapid fleeing to escape danger",                      anchor: rapid_fleeing,         weight: 1.0 }
  - { text: "Following pheromone trails during breeding",          anchor: pheromone_trailing,    weight: 1.0 }
  - { text: "Male combat to establish dominance",                  anchor: male_combat,           weight: 1.0 }
  - { text: "Courtship tail quiver near female",                   anchor: courtship_tail_quiver, weight: 1.0 }
  - { text: "Calm tongue flicking for exploration",                anchor: calm_tongue_flicking,  weight: 1.0 }

tie_groups:
  - [tail_vibration, defensive_hiss, body_flattening, s_coil_pose, bluff_strike, musking, freezing]

separate_groups:
  - [[tail_vibration, defensive_hiss, body_flattening, s_coil_pose, bluff_strike, musking, freezing],
     [calm_tongue_flicking, pheromone_trailing, courtship_tail_quiver, male_combat, rapid_fleeing]]
