species: crestedgecko

positive_pairs:
  - { text: "Slow tail waving as caution signal", anchor: tail_waving_slow_meaning, weight: 1.0 }
  - { text: "Rapid tail vibration",               anchor: tail_vibration_rapid_meaning, weight: 1.0 }
  - { text: "Scent rubbing on surfaces",          anchor: territorial_marking_meaning, weight: 1.0 }
  - { text: "2–5 short distress chirps",          anchor: distress_chirping_meaning, weight: 1.0 }
  - { text: "Barking-like call",                  anchor: barking_call_meaning, weight: 1.0 }
  - { text: "Head shaking indicates refusal",     anchor: head_shaking_meaning, weight: 1.0 }
  - { text: "Open-mouth threat display",          anchor: open_mouth_threat_meaning, weight: 1.0 }
  - { text: "Mating bite during copulation",      anchor: mating_bite_meaning, weight: 1.0 }
  - { text: "Escape jump to leave danger",        anchor: escape_jump_meaning, weight: 1.0 }
  - { text: "Tail autotomy as last-resort",       anchor: tail_autotomy_meaning, weight: 1.0 }
  - { text: "Fired-down calm coloration",         anchor: fired_down_calm_meaning, weight: 1.0 }

tie_groups:
  - [ tail_waving_slow_meaning, tail_vibration_rapid_meaning ]
  - [ open_mouth_threat_meaning, head_shaking_meaning ]

separate_groups:
  - [ exploration_meaning, open_mouth_threat_meaning ]
  - [ resting_calm_meaning, distress_chirping_meaning ]
