# configs/download.yaml
paths:
  raw_audio: "data/raw"
  clips_audio: "data/clips"
  meta: "data/meta"

audio:
  target_sr: 48000
  mono: true
  clip_len_sec: 10.0

# 원하는 라벨만 적기(원하면 추가/변경)
labels: ["Bark", "Howl", "Growling", "Whimper", "Yip", "Bow-wow"]


# ... 기존 항목 유지 + 아래만 추가/수정
audioset:
  csv_dir: "data/meta/audioset"
  use_balanced: true
  per_label_quota: 100     # 라벨별 목표 개수
  seed: 42
labels: ["Bark","Howl","Growling","Whimper","Yip","Bow-wow"]
paths:
  raw_audio: "data/raw"
  clips_audio: "data/clips"
  meta: "data/meta"
audio:
  target_sr: 48000
  mono: true
  clip_len_sec: 10.0
