name: gecko
language: en
anchors:
  # 소리 형태
  - chirp
  - click
  - squeak
  - trill
  # 기능/맥락
  - contact call
  - alarm call
  - distress call
  - courtship call
  - territorial display
  - aggressive display
  # 생활사/환경 힌트
  - nocturnal call
  - substrate vibration
