species: dog
anchors:
  - name: bark_alarm
    behavior_texts:
      - "short, rapid, loud barks"          # 관찰 가능한 형태(행동)
      - "staccato sequences with short gaps"
    meaning_texts:
      - "alarm / alert to potential threat"  # 기능적 해석(의미)
      - "territorial warning to intruders"
    context_texts:
      - "unknown human near door at night"   # 상황/환경(보조)
    labels:
      meaning: ["alarm", "threat", "territorial"]
      behavior: ["bark","rapid","loud"]

  - name: bark_playful
    behavior_texts:
      - "short single barks with wagging"
    meaning_texts:
      - "play invitation to familiar person"
    context_texts:
      - "owner returning home"
    labels:
      meaning: ["play","affiliative"]
      behavior: ["bark","short","single"]
